/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FindAssistanceRouteImport } from './routes/find-assistance'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as OutsideScopeRouteImport } from './routes/outside-scope'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrackRouteImport } from './routes/track'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAssistanceRoute = FindAssistanceRouteImport.update({
  id: '/find-assistance',
  path: '/find-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const OutsideScopeRoute = OutsideScopeRouteImport.update({
  id: '/outside-scope',
  path: '/outside-scope',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-assistance': typeof FindAssistanceRoute
  '/forms': typeof FormsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/outside-scope': typeof OutsideScopeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-assistance': typeof FindAssistanceRoute
  '/forms': typeof FormsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/outside-scope': typeof OutsideScopeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/find-assistance': typeof FindAssistanceRoute
  '/forms': typeof FormsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/knowledge': typeof KnowledgeRoute
  '/legal': typeof LegalRoute
  '/outside-scope': typeof OutsideScopeRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/tools': typeof ToolsRoute
  '/track': typeof TrackRoute
  '/updates': typeof UpdatesRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/find-assistance'
    | '/forms'
    | '/how-it-works'
    | '/knowledge'
    | '/legal'
    | '/outside-scope'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/tools'
    | '/track'
    | '/updates'
    | '/services/$slug'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/find-assistance'
    | '/forms'
    | '/how-it-works'
    | '/knowledge'
    | '/legal'
    | '/outside-scope'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/tools'
    | '/track'
    | '/updates'
    | '/services/$slug'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/find-assistance'
    | '/forms'
    | '/how-it-works'
    | '/knowledge'
    | '/legal'
    | '/outside-scope'
    | '/pricing'
    | '/resources'
    | '/security'
    | '/tools'
    | '/track'
    | '/updates'
    | '/services/$slug'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FindAssistanceRoute: typeof FindAssistanceRoute
  FormsRoute: typeof FormsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LegalRoute: typeof LegalRoute
  OutsideScopeRoute: typeof OutsideScopeRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  ToolsRoute: typeof ToolsRoute
  TrackRoute: typeof TrackRoute
  UpdatesRoute: typeof UpdatesRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-assistance': {
      id: '/find-assistance'
      path: '/find-assistance'
      fullPath: '/find-assistance'
      preLoaderRoute: typeof FindAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outside-scope': {
      id: '/outside-scope'
      path: '/outside-scope'
      fullPath: '/outside-scope'
      preLoaderRoute: typeof OutsideScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FindAssistanceRoute: FindAssistanceRoute,
  FormsRoute: FormsRoute,
  HowItWorksRoute: HowItWorksRoute,
  KnowledgeRoute: KnowledgeRoute,
  LegalRoute: LegalRoute,
  OutsideScopeRoute: OutsideScopeRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  ToolsRoute: ToolsRoute,
  TrackRoute: TrackRoute,
  UpdatesRoute: UpdatesRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
